# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        user:
            properties:
                username: ~
                firstName: ~
                lastName: ~
                email: ~
        app: ~
